/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupDetailedGroupIdRouteImport } from './routes/group/detailedGroupId'
import { Route as GroupCreateRouteImport } from './routes/group/create'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as Auth_layoutRouteImport } from './routes/auth/__layout'
import { Route as App_layoutRouteImport } from './routes/app/__layout'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppDashboardUsersRouteImport } from './routes/app/dashboard/users'
import { Route as AppDashboardGroupRouteImport } from './routes/app/dashboard/group'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupDetailedGroupIdRoute = GroupDetailedGroupIdRouteImport.update({
  id: '/group/detailedGroupId',
  path: '/group/detailedGroupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupCreateRoute = GroupCreateRouteImport.update({
  id: '/group/create',
  path: '/group/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_layoutRoute = Auth_layoutRouteImport.update({
  id: '/auth/__layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const App_layoutRoute = App_layoutRouteImport.update({
  id: '/app/__layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/app/dashboard/',
  path: '/app/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardUsersRoute = AppDashboardUsersRouteImport.update({
  id: '/app/dashboard/users',
  path: '/app/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardGroupRoute = AppDashboardGroupRouteImport.update({
  id: '/app/dashboard/group',
  path: '/app/dashboard/group',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof App_layoutRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/group/create': typeof GroupCreateRoute
  '/group/detailedGroupId': typeof GroupDetailedGroupIdRoute
  '/app/dashboard/group': typeof AppDashboardGroupRoute
  '/app/dashboard/users': typeof AppDashboardUsersRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof App_layoutRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/group/create': typeof GroupCreateRoute
  '/group/detailedGroupId': typeof GroupDetailedGroupIdRoute
  '/app/dashboard/group': typeof AppDashboardGroupRoute
  '/app/dashboard/users': typeof AppDashboardUsersRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/__layout': typeof App_layoutRoute
  '/auth/__layout': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/group/create': typeof GroupCreateRoute
  '/group/detailedGroupId': typeof GroupDetailedGroupIdRoute
  '/app/dashboard/group': typeof AppDashboardGroupRoute
  '/app/dashboard/users': typeof AppDashboardUsersRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/group/create'
    | '/group/detailedGroupId'
    | '/app/dashboard/group'
    | '/app/dashboard/users'
    | '/app/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/group/create'
    | '/group/detailedGroupId'
    | '/app/dashboard/group'
    | '/app/dashboard/users'
    | '/app/dashboard'
  id:
    | '__root__'
    | '/'
    | '/app/__layout'
    | '/auth/__layout'
    | '/auth/login'
    | '/auth/signup'
    | '/group/create'
    | '/group/detailedGroupId'
    | '/app/dashboard/group'
    | '/app/dashboard/users'
    | '/app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  App_layoutRoute: typeof App_layoutRoute
  Auth_layoutRoute: typeof Auth_layoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  GroupCreateRoute: typeof GroupCreateRoute
  GroupDetailedGroupIdRoute: typeof GroupDetailedGroupIdRoute
  AppDashboardGroupRoute: typeof AppDashboardGroupRoute
  AppDashboardUsersRoute: typeof AppDashboardUsersRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/detailedGroupId': {
      id: '/group/detailedGroupId'
      path: '/group/detailedGroupId'
      fullPath: '/group/detailedGroupId'
      preLoaderRoute: typeof GroupDetailedGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/create': {
      id: '/group/create'
      path: '/group/create'
      fullPath: '/group/create'
      preLoaderRoute: typeof GroupCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/__layout': {
      id: '/auth/__layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof Auth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/__layout': {
      id: '/app/__layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof App_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard/users': {
      id: '/app/dashboard/users'
      path: '/app/dashboard/users'
      fullPath: '/app/dashboard/users'
      preLoaderRoute: typeof AppDashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard/group': {
      id: '/app/dashboard/group'
      path: '/app/dashboard/group'
      fullPath: '/app/dashboard/group'
      preLoaderRoute: typeof AppDashboardGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  App_layoutRoute: App_layoutRoute,
  Auth_layoutRoute: Auth_layoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  GroupCreateRoute: GroupCreateRoute,
  GroupDetailedGroupIdRoute: GroupDetailedGroupIdRoute,
  AppDashboardGroupRoute: AppDashboardGroupRoute,
  AppDashboardUsersRoute: AppDashboardUsersRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
